# Site settings
# You can learn from website:http://jekyllcn.com/docs/configuration/

title: shdong
email: 630434698@qq.com
description: > # this means to ignore newlines until "baseurl:"
  shdong dongshihao blog font-end computer nodejs javascript
baseurl: "" # the subpath of your site, e.g. /blog
lang: "cn"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: shdong
github_username:  dongshihao

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
